# Numpy 
- numpy or numerical python is very powerful python library used to perform numerical operation on data. its written in c which gives us extra fast output. its work on GPU.its a backbone of data science.

In [1]:
# Import numpy
import numpy as np

### DATA TYPES AND ATTRIBUTES

In [64]:
# Numpy main datatypes is ndarray
a1 =  np.array([1,2,3])
a1

array([1, 2, 3])

In [65]:
a2 = np.array([[1,2.0,3.3],
             [4, 5, 6.6]])
a3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])


In [66]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [67]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### shape

In [68]:
# shape - return the (row, column)
a1.shape

(3,)

In [69]:
a2.shape

(2, 3)

In [70]:
a3.shape

(2, 3, 3)

### ndim

In [71]:
a1.ndim, a2.ndim, a3.ndim # return dimensions

(1, 2, 3)

### dtype

In [72]:
a1.dtype, a2.dtype, a3.dtype # return type

(dtype('int64'), dtype('float64'), dtype('int64'))

### size

In [73]:
a1.size, a2.size, a3.size #return no. of elemets in array

(3, 6, 18)

### type

In [74]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Create a DataFrame from Numpy Array

In [75]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.6

## CREATING ARRAYS

In [76]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [77]:
sample_array.dtype

dtype('int64')

### .ones() - return a new array of given shape and type, filled with ones. 

In [78]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [79]:
ones.dtype

dtype('float64')

In [80]:
type(ones)

numpy.ndarray

### .zeros() - Return a new array of given shape and type, filled with zeros.

In [81]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

### .arange() - arange(start, stop, step,) Return evenly spaced values within a given interval.

In [82]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

### random

In [83]:
random_array = np.random.randint(0,10, size=(3,5)) # return integer values in array
random_array

array([[6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0]], dtype=int32)

In [84]:
random_array.shape

(3, 5)

In [85]:
random_array.size

15

In [86]:
random_array_2 = np.random.random((5,3)) # return float values in array
random_array_2

array([[0.97861834, 0.79915856, 0.46147936],
       [0.78052918, 0.11827443, 0.63992102],
       [0.14335329, 0.94466892, 0.52184832],
       [0.41466194, 0.26455561, 0.77423369],
       [0.45615033, 0.56843395, 0.0187898 ]])

In [87]:
random_array_2.shape

(5, 3)

### rand

In [88]:
random_array_3 = np.random.rand(5,3) # return float values in array
random_array_3

array([[0.6176355 , 0.61209572, 0.616934  ],
       [0.94374808, 0.6818203 , 0.3595079 ],
       [0.43703195, 0.6976312 , 0.06022547],
       [0.66676672, 0.67063787, 0.21038256],
       [0.1289263 , 0.31542835, 0.36371077]])

### Pseudo-random numbers

In [89]:
np.random.seed(seed=0) # random change the values everytime we run this cell. while having seed function it will not change.
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4


array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [90]:
random_array_4.shape

(5, 3)

## VIEWING ARRAYS AND MATRICES

### unique - Find the unique elements of an array.

In [92]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [94]:
a1

array([1, 2, 3])

In [95]:
a2 

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [96]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [97]:
a1[0]

np.int64(1)

In [98]:
a2.shape

(2, 3)

In [99]:
a2[0]

array([1. , 2. , 3.3])

### slicing

In [100]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [102]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[8, 8, 2, 3, 2],
         [0, 8, 8, 3, 8],
         [2, 8, 4, 3, 0],
         [4, 3, 6, 9, 8]],

        [[0, 8, 5, 9, 0],
         [9, 6, 5, 3, 1],
         [8, 0, 4, 9, 6],
         [5, 7, 8, 8, 9]],

        [[2, 8, 6, 6, 9],
         [1, 6, 8, 8, 3],
         [2, 3, 6, 3, 6],
         [5, 7, 0, 8, 4]]],


       [[[6, 5, 8, 2, 3],
         [9, 7, 5, 3, 4],
         [5, 3, 3, 7, 9],
         [9, 9, 7, 3, 2]],

        [[3, 9, 7, 7, 5],
         [1, 2, 2, 8, 1],
         [5, 8, 4, 0, 2],
         [5, 5, 0, 8, 1]],

        [[1, 0, 3, 8, 8],
         [4, 4, 0, 9, 3],
         [7, 3, 2, 1, 1],
         [2, 1, 4, 2, 5]]]], dtype=int32)

In [103]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [105]:
# Get the 4 numbers of inner most array
a4[:, :, :, :2]

array([[[[8, 8],
         [0, 8],
         [2, 8],
         [4, 3]],

        [[0, 8],
         [9, 6],
         [8, 0],
         [5, 7]],

        [[2, 8],
         [1, 6],
         [2, 3],
         [5, 7]]],


       [[[6, 5],
         [9, 7],
         [5, 3],
         [9, 9]],

        [[3, 9],
         [1, 2],
         [5, 8],
         [5, 5]],

        [[1, 0],
         [4, 4],
         [7, 3],
         [2, 1]]]], dtype=int32)