# Numpy 
- numpy or numerical python is very powerful python library used to perform numerical operation on data. its written in c which gives us extra fast output. its work on GPU.its a backbone of data science.

In [1]:
# Import numpy
import numpy as np

### Data Types and Attributes

In [2]:
# Numpy main datatypes is ndarray
a1 =  np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1,2.0,3.3],
             [4, 5, 6.6]])
a3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])


In [4]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### shape

In [6]:
# shape - return the (row, column)
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

### ndim

In [13]:
a1.ndim, a2.ndim, a3.ndim # return dimensions

(1, 2, 3)

### dtype

In [14]:
a1.dtype, a2.dtype, a3.dtype # return type

(dtype('int64'), dtype('float64'), dtype('int64'))

### size

In [15]:
a1.size, a2.size, a3.size #return no. of elemets in array

(3, 6, 18)

### type

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Create a DataFrame from Numpy Array

In [20]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.6