# Numpy 
- numpy or numerical python is very powerful python library used to perform numerical operation on data. its written in c which gives us extra fast output. its work on GPU.its a backbone of data science.

In [1]:
# Import numpy
import numpy as np

### Data Types and Attributes

In [2]:
# Numpy main datatypes is ndarray
a1 =  np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1,2.0,3.3],
             [4, 5, 6.6]])
a3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])


In [4]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### shape

In [6]:
# shape - return the (row, column)
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

### ndim

In [13]:
a1.ndim, a2.ndim, a3.ndim # return dimensions

(1, 2, 3)

### dtype

In [14]:
a1.dtype, a2.dtype, a3.dtype # return type

(dtype('int64'), dtype('float64'), dtype('int64'))

### size

In [15]:
a1.size, a2.size, a3.size #return no. of elemets in array

(3, 6, 18)

### type

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Create a DataFrame from Numpy Array

In [20]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.6

## Creating Arrays

In [27]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [28]:
sample_array.dtype

dtype('int64')

### .ones() - return a new array of given shape and type, filled with ones. 

In [29]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
ones.dtype

dtype('float64')

In [31]:
type(ones)

numpy.ndarray

### .zeros() - Return a new array of given shape and type, filled with zeros.

In [33]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

### .arange() - arange(start, stop, step,) Return evenly spaced values within a given interval.

In [36]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

### random

In [42]:
random_array = np.random.randint(0,10, size=(3,5)) # return integer values in array
random_array

array([[8, 6, 3, 9, 2],
       [6, 1, 7, 3, 8],
       [2, 5, 8, 0, 4]], dtype=int32)

In [43]:
random_array.shape

(3, 5)

In [44]:
random_array.size

15

In [47]:
random_array_2 = np.random.random((5,3)) # return float values in array
random_array_2

array([[0.29583987, 0.03637933, 0.7355098 ],
       [0.57096933, 0.94469979, 0.38808864],
       [0.84353125, 0.06930533, 0.0326859 ],
       [0.54334682, 0.07124548, 0.58533632],
       [0.70381686, 0.90592091, 0.72160898]])

In [48]:
random_array_2.shape

(5, 3)

### rand

In [49]:
random_array_3 = np.random.rand(5,3) # return float values in array
random_array_3

array([[0.78347187, 0.98247296, 0.36792891],
       [0.25166944, 0.79847765, 0.30438023],
       [0.98607656, 0.00266533, 0.67433545],
       [0.11226519, 0.25744819, 0.41563878],
       [0.3630208 , 0.39311305, 0.81031329]])

### Pseudo-random numbers

In [60]:
np.random.seed(seed=0) # random change the values everytime we run this cell. while having seed function it will not change.
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4


array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [62]:
random_array_4.shape

(5, 3)