# Numpy 
- numpy or numerical python is very powerful python library used to perform numerical operation on data. its written in c which gives us extra fast output. its work on GPU.its a backbone of data science.
- Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

In [1]:
# Import numpy
import numpy as np

### DATA TYPES AND ATTRIBUTES

In [64]:
# Numpy main datatypes is ndarray
a1 =  np.array([1,2,3])
a1

array([1, 2, 3])

In [65]:
a2 = np.array([[1,2.0,3.3],
             [4, 5, 6.6]])
a3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])


In [66]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [67]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### shape

In [68]:
# shape - return the (row, column)
a1.shape

(3,)

In [69]:
a2.shape

(2, 3)

In [70]:
a3.shape

(2, 3, 3)

### ndim

In [71]:
a1.ndim, a2.ndim, a3.ndim # return dimensions

(1, 2, 3)

### dtype

In [72]:
a1.dtype, a2.dtype, a3.dtype # return type

(dtype('int64'), dtype('float64'), dtype('int64'))

### size

In [73]:
a1.size, a2.size, a3.size #return no. of elemets in array

(3, 6, 18)

### type

In [74]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Create a DataFrame from Numpy Array

In [75]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.6

## CREATING ARRAYS

In [76]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [77]:
sample_array.dtype

dtype('int64')

### .ones() 
- return a new array of given shape and type, filled with ones. 

In [78]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [79]:
ones.dtype

dtype('float64')

In [80]:
type(ones)

numpy.ndarray

### .zeros() 
- Return a new array of given shape and type, filled with zeros.

In [81]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

### .arange() 
- arange(start, stop, step,) Return evenly spaced values within a given interval.

In [82]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

### random
- Random Number Generation

In [83]:
random_array = np.random.randint(0,10, size=(3,5)) # return integer values in array
random_array

array([[6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0]], dtype=int32)

In [84]:
random_array.shape

(3, 5)

In [85]:
random_array.size

15

In [86]:
random_array_2 = np.random.random((5,3)) # return float values in array
random_array_2

array([[0.97861834, 0.79915856, 0.46147936],
       [0.78052918, 0.11827443, 0.63992102],
       [0.14335329, 0.94466892, 0.52184832],
       [0.41466194, 0.26455561, 0.77423369],
       [0.45615033, 0.56843395, 0.0187898 ]])

In [87]:
random_array_2.shape

(5, 3)

### rand
- Random values in a given shape.

In [88]:
random_array_3 = np.random.rand(5,3) # return float values in array
random_array_3

array([[0.6176355 , 0.61209572, 0.616934  ],
       [0.94374808, 0.6818203 , 0.3595079 ],
       [0.43703195, 0.6976312 , 0.06022547],
       [0.66676672, 0.67063787, 0.21038256],
       [0.1289263 , 0.31542835, 0.36371077]])

### Pseudo-random numbers
### seed
- Reseed the singleton RandomState instance.

In [89]:
np.random.seed(seed=0) # random change the values everytime we run this cell. while having seed function it will not change.
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4


array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [90]:
random_array_4.shape

(5, 3)

## VIEWING ARRAYS AND MATRICES

### unique - Find the unique elements of an array.

In [92]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [94]:
a1

array([1, 2, 3])

In [95]:
a2 

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [96]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [97]:
a1[0]

np.int64(1)

In [98]:
a2.shape

(2, 3)

In [99]:
a2[0]

array([1. , 2. , 3.3])

### slicing

In [100]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [102]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[8, 8, 2, 3, 2],
         [0, 8, 8, 3, 8],
         [2, 8, 4, 3, 0],
         [4, 3, 6, 9, 8]],

        [[0, 8, 5, 9, 0],
         [9, 6, 5, 3, 1],
         [8, 0, 4, 9, 6],
         [5, 7, 8, 8, 9]],

        [[2, 8, 6, 6, 9],
         [1, 6, 8, 8, 3],
         [2, 3, 6, 3, 6],
         [5, 7, 0, 8, 4]]],


       [[[6, 5, 8, 2, 3],
         [9, 7, 5, 3, 4],
         [5, 3, 3, 7, 9],
         [9, 9, 7, 3, 2]],

        [[3, 9, 7, 7, 5],
         [1, 2, 2, 8, 1],
         [5, 8, 4, 0, 2],
         [5, 5, 0, 8, 1]],

        [[1, 0, 3, 8, 8],
         [4, 4, 0, 9, 3],
         [7, 3, 2, 1, 1],
         [2, 1, 4, 2, 5]]]], dtype=int32)

In [103]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [106]:
# Get the 4 numbers of inner most array
a4[:, :, :2, :2]

array([[[[8, 8],
         [0, 8]],

        [[0, 8],
         [9, 6]],

        [[2, 8],
         [1, 6]]],


       [[[6, 5],
         [9, 7]],

        [[3, 9],
         [1, 2]],

        [[1, 0],
         [4, 4]]]], dtype=int32)

## MANIPULATING & COMPARING ARRAYS

### Arithmetic

In [107]:
a1

array([1, 2, 3])

In [108]:
ones = np.ones(3)
ones

array([1., 1., 1.])

### Add
- Add arguments, element-wise.

In [123]:
np.add(a1, ones)

array([2., 3., 4.])

In [109]:
a1 + ones

array([2., 3., 4.])

### Subtract 
- Subtract arguments, element-wise.

In [124]:
np.subtract(a1, ones)

array([0., 1., 2.])

In [110]:
a1 - ones

array([0., 1., 2.])

### Multiply
- Multiply arguments element-wise.

In [125]:
np.multiply(a1, a2)

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.8]])

In [111]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.8]])

### Division
- Divide arguments element-wise.

In [126]:
np.divide(a1, ones)

array([1., 2., 3.])

In [114]:
a1 / ones

array([1., 2., 3.])

In [115]:
a2 / a1

array([[1. , 1. , 1.1],
       [4. , 2.5, 2.2]])

### Floor Division - removes the decimals (rounds down).
- Return the largest integer smaller or equal to the division of the inputs.

In [153]:
np.floor_divide(a2, a1)

array([[1., 1., 1.],
       [4., 2., 2.]])

In [117]:
a2 // a1 

array([[1., 1., 1.],
       [4., 2., 2.]])

In [118]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

### Square
- Return the element-wise square of the input.


In [122]:
np.square(a2) 

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 43.56]])

In [120]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 43.56]])

### Modulo(reminder)
- 
Returns the element-wise remainder of division.

In [129]:
np.mod(a2, 2)

array([[1. , 0. , 1.3],
       [0. , 1. , 0.6]])

In [127]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.6]])

### Exponential
- Calculate the exponential of all elements in the input array.

In [130]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

### Log
- Natural logarithm, element-wise.

In [134]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation - performing the same operation on number of things.

In [136]:
listy_list = [1, 2, 3]
listy_list

[1, 2, 3]

In [137]:
sum(listy_list)

6

Note:
Use Python's method ` sum() ` on Python datatype's and use Numpy methods on Numpy's arrays ` np.sum() ` 

In [138]:
# Creative a massive Numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [141]:
massive_array[:10]

array([0.21874937, 0.56957353, 0.45210904, 0.97023668, 0.68054469,
       0.08529557, 0.05641833, 0.4878377 , 0.88100456, 0.97640439])

### Calculating time of Python function and Numpy function.

In [142]:
%timeit sum(massive_array) #Python's sum()
%timeit np.sum(massive_array) #Numpy's sum()

10.4 ms ± 81.9 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
58.7 μs ± 756 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [143]:
10400 / 34

305.88235294117646

In [144]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

### mean
- Compute the arithmetic mean along the specified axis

In [145]:
np.mean(a2)

np.float64(3.65)

### min
Return the minimum of an array or minimum along an axis.


In [146]:
np.min(a2)

np.float64(1.0)

### max
Return the maximum of an array or maximum along an axis.


In [147]:
np.max(a2)

np.float64(6.6)

### std (Standard deviation)- Compute the standard deviation along the specified axis.
- how much the values in a dataset vary from the mean.
- a measure of how spread out a group of numbers is from the mean.

In [149]:
np.std(a2)

np.float64(1.8490988796347985)

### var - Variance
- Compute the variance along the specified axis.
- measure of the average degree to which each number is different to the mean.
- High variance = wider range of numbers
- Lower variance = lower range of numbers

In [150]:
np.var(a2)

np.float64(3.419166666666667)

### Standard deviation = Squareroot of variance

In [151]:
np.sqrt(np.var(a2))

np.float64(1.8490988796347985)